### PR TITLE
Defs 2289 Init Project

### PR DESCRIPTION
**Pull request by ducvu212**
# Sumary
- Init Project
# Redmine
-https://edu-redmine.framgia.vn/issues/2289?issue_count=74&issue_position=73&next_issue_id=2288&prev_issue_id=2290
# Buglist

### CODE REVIEW

**Comment by DoanVanToan** [comment]
ready

**Comment by DoanVanToan** [comment]
merged

**Comment by DoanVanToan** [comment]
ready

**Comment by ducvu212** [comment]
ready

**Comment by ducvu212** [comment]
ready

**Comment by baclv** [comment]
ready

**Comment by ducvu212** [comment]
ready

**Comment by ducvu212** [comment]
ready

**Comment by ducvu212** [comment]
ready

**Comment by ducvu212** [comment]
ready

**Comment by ducvu212** [comment]
ready

**Comment by ducvu212** [comment]
ready

**Comment by ducvu212** [comment]
ready

**Comment by hungth-1726** [comment]
ready

**Review by tuanlvt-1117 — APPROVED** [review]

**Pull request merged**
